name: 'Suggest a Feature'
description: 'Suggest a Feature or Enhancement for USB Construct'
type: 'Feature'
labels: [
  'enhancement'
]

body:
  - type: markdown
    attributes:
      value: '## Suggest a Feature or Enhancement for USB Construct'
  - type: markdown
    attributes:
      value: >
        Thank you for wanting to help make USB Construct even better and feature packed for everyone!


        Before you continue, try to check if what you're suggesting has already been requested
        before, you can use the filter `is:issue label:enhancement type:Feature` in the USB Construct
        [issue tracker](https://github.com/shrine-maiden-heavy-industries/usb-construct/issues)
        to search, or [use this pre-defined filter](https://github.com/shrine-maiden-heavy-industries/usb-construct/issues?q=is%3Aissue%20label%3Aenhancement%20type%3AFeature)


        Also, make sure to review the [Contribution Guidelines](https://github.com/shrine-maiden-heavy-industries/usb-construct/blob/main/CONTRIBUTING.md#suggesting-features).

  - type: textarea
    id: feature-description
    attributes:
      label: 'Feature Description'
      description: >
        Please provide as detailed of a suggestion as possible, such as use cases and upsides, as well as
        any possible downsides or implementation issues you can possibly foresee.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 'Code of Conduct'
      description: >
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/shrine-maiden-heavy-industries/usb-construct/blob/main/CODE_OF_CONDUCT.md)
        and [AI usage Policy](https://github.com/shrine-maiden-heavy-industries/usb-construct/blob/main/CONTRIBUTING.md#ai-usage-policy).
      options:
        - label: 'I agree to follow the USB Construct Code of Conduct and AI Usage Policy'
          required: true
